### ISSUE TITLE
File Monitor does not update when log is cleared

### ISSUE THREAD

**Issue by octocat-mona** [ishegatron/Sentinel#7]
My log file is recreated every time my app starts. When Sentinel already logged some entries and the log file is cleared afterwards, the old log entries do not vanish.

**Steps to reproduce:**
1. Add File logger.
2. Add entries to the log file.
3. Clear the log file and add a new entry.
4. The new entry is not logged.

**Comment by ishegatron** [comment]
@kpstolk I noticed the FlieMonitoringProvider was not creating log entries correctly.  Perhaps my newest commit fixes this issue?

**Comment by octocat-mona** [comment]
@ishegatron I did not encounter that issue, can you check if this happens when you follow the same steps I do?:
1. Open new session and add a File Monitoring Provider to an existing default NLog log file.
2. Check the box _Load existing content from log file_
3. When you have finished the wizard the existing and new log entries should be shown.

In my case I did not see any difference before or after your fix ..

**Comment by ishegatron** [comment]
@kpstolk The File Monitoring Provider does not work at all (without my fix) when I follow your steps.  It throws a NullReferenceException as soon as the wizard closes and does not show any log entries.  Perhaps your development environment is set to ignore this error?

Clearing the log file does not clear the Sentinel display, which I think was the intended behavior.  But it does reset the log entry count, which probably should keep increasing despite what happens in the log file.

**Comment by octocat-mona** [comment]
@ishegatron I just checked out commit f469e0288e2080673cfc674956e94d28c1475b12 and when I just run it I do not get an error.

Can you post what error / stacktrace you get?

I do however get an error when loading a saved session, but I guess that that is another issue which needs to be fixed.

**Comment by ishegatron** [comment]
@kpstolk Here's my stack trace:

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Sentinel
  StackTrace:
       at Sentinel.Classification.Classifier.Classify(ILogEntry entry) in c:\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel\Classification\Classifier.cs:line 193
       at Sentinel.Classification.ClassifyingService`1.<Classify>b__b(ILogEntry current, T classifier) in c:\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel\Classification\ClassifyingService.cs:line 163
       at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
       at Sentinel.Classification.ClassifyingService`1.Classify(ILogEntry entry) in c:\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel\Classification\ClassifyingService.cs:line 161
       at Sentinel.Logs.Log.AddBatch(Queue`1 entries) in c:\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel\Logs\Log.cs:line 110
       at Sentinel.FileMonitor.FileMonitoringProvider.PurgeWorkerDoWork(Object sender, DoWorkEventArgs e) in c:\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel-f469e0288e2080673cfc674956e94d28c1475b12\Sentinel.FileMonitor\FileMonitoringProvider.cs:line 113
       at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
  InnerException: 
```

I also get an error when opening a saved session; I've opened a separate issue to keep track of it.

**Comment by ishegatron** [comment]
@kpstolk Commit c601943a6c867c366f3c70ac3672b695f270d1b4 clears log entries from Sentinel when the file is cleared.
